### ISSUE TITLE
Icon displayed multiple times

### ISSUE THREAD

**Issue by ms3056** [yoyurec/logseq-banners-plugin#53]
Hi - I am having the little calendar icon appear multiple times. Is there any way to remove this? 
![image](https://user-images.githubusercontent.com/23712700/184588701-d494e117-4b92-489e-b8dc-27fa1c5d7e37.png)

**Comment by yoyurec** [comment]
Page icon as a calendar - it's a feature.
1st Journal item has big one, next items - small.

BUT icon near Deadline block - it's a bug.

**Comment by yoyurec** [comment]
to hide:
```css
body[data-page="home"].is-icon-active #journals .journal-item h1.title::before {
    display: none;
}
```
