### ISSUE TITLE
Quote width setting

### ISSUE THREAD

**Issue by ms3056** [yoyurec/logseq-banners-plugin#55]
I would like a way to force the quote window to be narrower and taller. The widget used to do this but but now it seems like the widge only wants to be 2 lines tall and it interferes in my setup. I have the right panel open at all times. 

![image](https://user-images.githubusercontent.com/23712700/185008666-3df9af07-e953-4f11-bca1-af6155cd3d01.png)

**Comment by yoyurec** [comment]
now it's 48 characters. you can set yours. or in px
```css
#banner-widgets-quote-block {
    max-width: 48ch; 
}
```
